#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Joel Kuzmarski <leoj3n@gmail.com>
#
# Notes:
#   - https://github.com/sorin-ionescu/prezto/pull/494
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vi'
export VISUAL='subl'
export GIT_EDITOR='vi'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Go
#

export GOPATH='/Users/leoj/.go'

#
# Homebrew
#

export HOMEBREW_GITHUB_API_TOKEN='e9adc10205e39a885c58f1d6534510ce752d448b'

#
# Paths
#

typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /Applications/Sublime\ Text.app/Contents/SharedSupport/bin
  /usr/local/opt/php54/bin
  /Users/leoj/Documents/Sys\ Adm/bin
  # /usr/local/{bin,sbin} # Homebrew wants /usr/local/bin at front of $PATH...
  /usr/local/sbin         # We do that in /etc/paths and keep here /sbin
  /usr/local/mysql/bin
  $HOME/.composer/bin
  $HOME/.rvm/bin
  # $GOPATH/bin
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi


#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

