#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# -------- Customize to your needs...

# Vassh

source /Users/leoj/Documents/Sys\ Adm/Scripts/vassh.sh

# WP-CLI Bash completions

autoload bashcompinit
bashcompinit
source $HOME/.composer/vendor/wp-cli/wp-cli/utils/wp-completion.bash

# Git Bash Completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  #. $(brew --prefix)/etc/bash_completion
fi

# Defaults

# Always open everything in Finder's list view

defaults write com.apple.Finder FXPreferredViewStyle Nlsv

# Aliases

## Git

# ---
#alias hub="$GOPATH/bin/gh"
eval "$(hub alias -s)"
# ---
alias ngh="/usr/local/bin/gh"
alias gcam="gca -m"
alias gfa="gf --all"
alias gpuo="gp -u origin"
alias gpuom="gp -u origin master"
function gbp() { gf origin pull/$1/head:$2; }
alias gih="g update-index --assume-unchanged"
alias gis="g update-index --no-assume-unchanged"
alias grm="git status | grep deleted | awk '{print \$3}' | xargs git rm"
function gcap() { foo=$1; g mv --force $foo "$(tr '[:lower:]' '[:upper:]' <<< ${foo:0:1})${foo:1}"; }

## Roots

alias reroots="rm -rf rootstheme.com && gfc -p retlehs/rootstheme.com && cd rootstheme.com && vu"

## Other

alias v="vassh"
alias t="type"
alias c="clear"
alias ep="sublp"
alias se="smartextract"
alias ...="cd ../.."
# alias -- -="cd -" # not working in zsh prezto
alias lsd="ls -Ad .*"
alias vu="vagrant up"
alias vs="vagrant ssh"
alias vh="vagrant halt"
alias vr="vagrant reload"
alias vd="vagrant destroy"
alias vp="vagrant provision"
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to pasteboard.'"
alias kextl="sudo kextload /System/Library/Extensions/AppleUSBTopCase.kext/Contents/PlugIns/AppleUSBTCKeyboard.kext"
alias kextu="sudo kextunload /System/Library/Extensions/AppleUSBTopCase.kext/Contents/PlugIns/AppleUSBTCKeyboard.kext > /dev/null 2>&1"
alias flush="dscacheutil -flushcache" # Flush Directory Service cache
alias whois="whois -h whois-servers.net"
alias wanip="dig +short myip.opendns.com @resolver1.opendns.com"
alias ss="open /System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app"
# View HTTP traffic
#alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

# Functions

function h() {
  cd ~/$1;
}

function sublp() {
  proj=~/Documents/Sublime/$1.sublime-project
  subl --project $proj

  # print project folders
  awk -F"[,:]" '{for(i=1;i<=NF;i++){if($i~/path\042/){print $(i+1)} } }' $proj
}

## Derrived from: http://www.commandlinefu.com/commands/view/6110/create-an-animated-gif-from-a-youtube-video

function ytgif() {
  tmp=".ytgif";
  flv="$tmp/yt.flv";
  rnd="$tmp/$RANDOM";
  youtube-dl -o "$flv" $1;
  ytsize=$(wc -c < $flv);
  mplayer $flv -endpos $[ytsize*.75]"b" -sstep 30 -vo jpeg:outdir="$rnd":smooth=30:progressive -vf scale=320:240 -nosound;
  convert -delay 30 -loop 0 "$rnd/*.jpg" yt.gif;
  rm -rf "$rnd";
  rm -ri .ytgif;
}

## From http://stackoverflow.com/questions/370047/#370255

function path_remove() {
  IFS=:
  # convert it to an array
  t=($PATH)
  unset IFS
  # perform any array operations to remove elements from the array
  t=(${t[@]%%$1})
  IFS=:
  # output the new array
  echo "${t[*]}"
}

## credit: http://nparikh.org/notes/zshrc.txt
## Usage: smartextract <file>
## Description: extracts archived files / mounts disk images
## Note: .dmg/hdiutil is Mac OS X-specific.

smartextract () {
    if [ -f $1 ]; then
        case $1 in
            *.tar.bz2)  tar -jxvf $1                        ;;
            *.tar.gz)   tar -zxvf $1                        ;;
            *.bz2)      bunzip2 $1                          ;;
            *.dmg)      hdiutil mount $1                    ;;
            *.gz)       gunzip $1                           ;;
            *.tar)      tar -xvf $1                         ;;
            *.tbz2)     tar -jxvf $1                        ;;
            *.tgz)      tar -zxvf $1                        ;;
            *.zip)      unzip $1                            ;;
            *.ZIP)      unzip $1                            ;;
            *.pax)      cat $1 | pax -r                     ;;
            *.pax.Z)    uncompress $1 --stdout | pax -r     ;;
            *.Z)        uncompress $1                       ;;
            *)          echo "'$1' cannot be extracted/mounted via smartextract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}
